from ._base import PresetNodeBase

# Character presets — each a flat tuple of visual tags (hair / build /
# outfit) that together evoke an archetype.
PRESETS: dict[str, tuple[str, ...]] = {
    # ── Existing presets ──────────────────────────────────────────────────
    "miko": (
        "long_hair",
        "black_hair",
        "bangs",
        "miko",
        "hakama",
        "tabi",
        "zouri",
        "shrine_outdoors",
    ),
    "serafuku_schoolgirl": (
        "long_hair",
        "black_hair",
        "bangs",
        "hair_ribbon",
        "serafuku",
        "sailor_collar",
        "pleated_skirt",
        "thighhighs",
        "loafers",
    ),
    "blazer_schoolgirl": (
        "medium_hair",
        "brown_hair",
        "blazer_uniform",
        "blouse",
        "pleated_skirt",
        "cardigan",
        "pantyhose",
        "loafers",
    ),
    "maid": (
        "long_hair",
        "twin_braids",
        "black_hair",
        "maid",
        "frilled_apron",
        "headband",
        "thighhighs",
        "mary_janes",
    ),
    "nurse": (
        "short_hair",
        "brown_hair",
        "medium_breasts",
        "nurse",
        "nurse_cap",
        "pantyhose",
        "loafers",
    ),
    "office_lady": (
        "medium_hair",
        "black_hair",
        "business_suit",
        "blouse",
        "pencil_skirt",
        "pantyhose",
        "high_heels",
        "glasses",
    ),
    "witch": (
        "very_long_hair",
        "purple_hair",
        "witch",
        "witch_hat",
        "long_dress",
        "thighhighs",
        "boots",
    ),
    "cheerleader": (
        "twintails",
        "orange_hair",
        "hair_ribbon",
        "cheerleader",
        "miniskirt",
        "socks",
        "sneakers",
    ),
    "yukata_festival": (
        "long_hair",
        "hair_bun",
        "ahoge",
        "hair_flower",
        "yukata",
        "obi",
        "tabi",
        "geta",
    ),
    "bunny_girl": (
        "long_hair",
        "ponytail",
        "black_hair",
        "bunny_girl",
        "bunny_ears",
        "rabbit_tail",
        "fishnets",
        "pantyhose",
        "high_heels",
    ),
    "princess": (
        "very_long_hair",
        "drill_hair",
        "blonde_hair",
        "pale_skin",
        "ball_gown",
        "tiara",
        "necklace",
        "elbow_gloves",
        "high_heels",
    ),
    "gothic_lolita": (
        "long_hair",
        "twin_drills",
        "black_hair",
        "pale_skin",
        "frilled_dress",
        "lace",
        "frills",
        "headband",
        "thighhighs",
        "mary_janes",
        "frilled_choker",
    ),
    "nun": (
        "long_hair",
        "silver_hair",
        "nun",
        "veil",
        "long_dress",
        "necklace",
    ),
    "kunoichi": (
        "long_hair",
        "ponytail",
        "black_hair",
        "toned",
        "kunoichi",
        "skin_tight",
        "tabi",
        "scarf_over_mouth",
    ),
    "catgirl_basic": (
        "long_hair",
        "cat_ears",
        "cat_tail",
        "yellow_eyes",
        "slit_pupils",
        "fang",
    ),
    "vampire": (
        "long_hair",
        "black_hair",
        "pale_skin",
        "pointy_ears",
        "fangs",
        "red_eyes",
        "cape",
        "long_dress",
    ),
    "santa_girl": (
        "long_hair",
        "twintails",
        "red_hair",
        "santa_costume",
        "santa_hat",
        "fur_trim",
        "thighhighs",
        "knee_boots",
    ),
    "knight": (
        "long_hair",
        "ponytail",
        "blonde_hair",
        "toned",
        "abs",
        "armor",
        "gauntlets",
        "pauldron",
        "vambraces",
        "cape",
        "knee_boots",
    ),
    "magical_girl": (
        "long_hair",
        "twintails",
        "pink_hair",
        "frilled_dress",
        "hair_ribbon",
        "tiara",
        "thighhighs",
        "mary_janes",
        "sparkles",
    ),
    "yandere_schoolgirl": (
        "very_long_hair",
        "black_hair",
        "red_eyes",
        "yandere",
        "smirk",
        "narrowed_eyes",
        "heart-shaped_pupils",
        "serafuku",
    ),
    # ── New presets ───────────────────────────────────────────────────────
    "idol_popstar": (
        "twintails",
        "pink_hair",
        "idol_clothes",
        "star_hair_ornament",
        "frills",
        "thighhighs",
        "mary_janes",
        "smile",
        "sparkles",
        "stage",
    ),
    "teacher_sensei": (
        "medium_hair",
        "brown_hair",
        "glasses",
        "blouse",
        "pencil_skirt",
        "blazer",
        "pantyhose",
        "high_heels",
        "blackboard",
    ),
    "delinquent_girl": (
        "long_hair",
        "blonde_hair",
        "dyed_hair",
        "open_jacket",
        "tank_top",
        "miniskirt",
        "fishnet_stockings",
        "platform_footwear",
        "scowl",
    ),
    "police_officer": (
        "short_hair",
        "black_hair",
        "police_uniform",
        "handcuffs",
        "belt",
        "looking_at_viewer",
        "serious",
    ),
    "pirate_captain": (
        "long_hair",
        "red_hair",
        "bicorne",
        "pirate",
        "coat",
        "boots",
        "eyepatch",
        "scar_on_cheek",
    ),
    "elf_archer": (
        "very_long_hair",
        "blonde_hair",
        "pointy_ears",
        "tunic",
        "holding_bow_(weapon)",
        "quiver",
        "green_eyes",
        "forest",
    ),
    "samurai_girl": (
        "long_hair",
        "black_hair",
        "ponytail",
        "kimono",
        "hakama_skirt",
        "holding_katana",
        "japanese_clothes",
    ),
    "military_officer": (
        "short_hair",
        "black_hair",
        "military_uniform",
        "peaked_cap",
        "epaulettes",
        "boots",
        "looking_at_viewer",
    ),
    "fantasy_cleric": (
        "very_long_hair",
        "white_hair",
        "robe",
        "cross",
        "necklace",
        "holding_wand",
        "pale_skin",
        "church",
    ),
    "dojo_fighter": (
        "short_hair",
        "black_hair",
        "ponytail",
        "dougi",
        "barefoot",
        "determined",
        "serious",
        "fighting_stance",
    ),
    "android_gynoid": (
        "short_hair",
        "silver_hair",
        "bodysuit",
        "glowing_eyes",
        "mechanical_parts",
        "expressionless",
        "visor",
    ),
    "detective_noir": (
        "medium_hair",
        "black_hair",
        "trench_coat",
        "beret",
        "scar_on_cheek",
        "serious",
        "indoors",
    ),
    "gyaru": (
        "long_hair",
        "blonde_hair",
        "tan",
        "tanlines",
        "crop_top",
        "miniskirt",
        "platform_heels",
        "smirk",
        "nail_polish",
    ),
    "fantasy_mage": (
        "very_long_hair",
        "purple_hair",
        "robe",
        "holding_wand",
        "pointed_hat",
        "thighhighs",
        "boots",
        "sparkles",
    ),
    "idol_unit_uniform": (
        "short_hair",
        "orange_hair",
        "idol_clothes",
        "pleated_skirt",
        "frills",
        "thighhighs",
        "smile",
        "holding_microphone",
        "stage",
    ),
    "cafe_waitress": (
        "medium_hair",
        "hair_ribbon",
        "waitress",
        "frilled_apron",
        "blouse",
        "short_skirt",
        "mary_janes",
        "smile",
    ),
    "race_queen": (
        "short_hair",
        "brown_hair",
        "race_queen",
        "hair_ornament",
        "thighhighs",
        "high_heels",
        "looking_at_viewer",
    ),
    "shrine_dancer": (
        "long_hair",
        "black_hair",
        "hair_ornament",
        "miko",
        "white_dress",
        "dancing",
        "barefoot",
        "shrine_outdoors",
    ),
    "futuristic_idol": (
        "long_hair",
        "multicolored_hair",
        "idol_clothes",
        "holographic",
        "neon_trim",
        "thigh_boots",
        "smile",
        "sparkles",
    ),
    "pirate_navigator": (
        "short_hair",
        "orange_hair",
        "pirate",
        "jacket",
        "shorts",
        "knee_boots",
        "telescope",
    ),
}


class CharacterPreset(PresetNodeBase):
    PRESETS = PRESETS
    PARAM = "preset"
    LAYER = "preset"


NODE_CLASS_MAPPINGS: dict[str, type] = {"UtilityNodesCharacterPreset": CharacterPreset}
NODE_DISPLAY_NAME_MAPPINGS: dict[str, str] = {"UtilityNodesCharacterPreset": "Character"}
