from ._base import PresetNodeBase

# NSFW act presets — bundle act / position / state / expression tags that
# frequently appear together. Designed to layer on top of CharacterPreset
# (visuals) and PersonalityPreset (mood) via TagsBuild.
#
# Location-based pairings are intentionally NOT here — use a SituationPreset
# for the setting and layer this node on top. e.g. `hospital_ward` situation
# + `breast_play` act, or `hot_spring` situation + `vanilla_missionary` act.
#
# Conflicts with non-NSFW clothing presets are resolved automatically
# (e.g. `nude`-containing presets drop competing outfit tags).
NSFW_ACT_PRESETS: dict[str, tuple[str, ...]] = {
    # ── Penetrative ───────────────────────────────────────────────────────
    "vanilla_missionary": (
        "missionary",
        "vaginal",
        "kissing",
        "french_kiss",
        "nude",
        "blush",
        "parted_lips",
        "closed_eyes",
        "on_back",
    ),
    "doggystyle": (
        "doggystyle",
        "sex_from_behind",
        "arched_back",
        "all_fours",
        "ahegao",
        "heart-shaped_pupils",
        "tongue_out",
        "nude",
    ),
    "mating_press": (
        "mating_press",
        "ahegao",
        "heart-shaped_pupils",
        "on_back",
        "sweat",
        "blush",
        "nude",
        "tongue_out",
    ),
    "cowgirl_riding": (
        "cowgirl_position",
        "vaginal",
        "moaning",
        "blush",
        "looking_at_viewer",
        "open_mouth",
        "smirk",
        "nude",
    ),
    "reverse_cowgirl": (
        "reverse_cowgirl_position",
        "vaginal",
        "moaning",
        "blush",
        "looking_back",
        "nude",
        "sweat",
    ),
    "prone_bone": (
        "prone_bone",
        "sex_from_behind",
        "ahegao",
        "nude",
        "on_stomach",
        "sweat",
        "heart-shaped_pupils",
    ),
    "wall_slam": (
        "wall_slam",
        "standing_sex",
        "vaginal",
        "blush",
        "nude",
        "looking_at_viewer",
        "open_mouth",
    ),
    "lotus_embrace": (
        "lotus_position",
        "vaginal",
        "kissing",
        "nude",
        "blush",
        "closed_eyes",
        "smile",
    ),
    "full_nelson_ahegao": (
        "full_nelson",
        "vaginal",
        "ahegao",
        "heart-shaped_pupils",
        "nude",
        "sweat",
    ),
    "leg_lock_deep": (
        "leg_lock",
        "vaginal",
        "cum_in_pussy",
        "blush",
        "looking_at_viewer",
        "nude",
        "ahegao",
    ),
    "suspended_sex": (
        "suspended_congress",
        "vaginal",
        "nude",
        "blush",
        "moaning",
    ),
    "spooning_tender": (
        "spooning",
        "vaginal",
        "kissing",
        "nude",
        "blush",
        "smile",
    ),
    "spitroast": (
        "spitroast",
        "fellatio",
        "vaginal",
        "ahegao",
        "nude",
        "sweat",
    ),
    "double_penetration": (
        "double_penetration",
        "ahegao",
        "nude",
        "sweat",
        "heart-shaped_pupils",
    ),
    "gangbang_rough": (
        "gangbang",
        "rough_sex",
        "nude",
        "ahegao",
        "tears",
        "sweat",
    ),
    "clothed_sex": (
        "clothes_lift",
        "vaginal",
        "on_back",
        "blush",
        "embarrassed",
        "tearful",
    ),
    "first_time_shy": (
        "vaginal",
        "missionary",
        "embarrassed",
        "blush",
        "tearful",
        "parted_lips",
        "nude",
        "closed_eyes",
    ),
    # ── Anal ──────────────────────────────────────────────────────────────
    "anal_focus": (
        "anal",
        "anal_doggystyle",
        "cum_in_ass",
        "spread_ass",
        "presenting",
        "ahegao",
        "on_stomach",
    ),
    # ── Oral ──────────────────────────────────────────────────────────────
    "fellatio_pov": (
        "fellatio",
        "cum_in_mouth",
        "saliva",
        "saliva_trail",
        "closed_eyes",
        "blush",
        "kneeling",
    ),
    "cunnilingus_receive": (
        "cunnilingus",
        "spread_legs",
        "blush",
        "moaning",
        "closed_eyes",
        "nude",
        "on_back",
        "sweat",
    ),
    "irrumatio_rough": (
        "irrumatio",
        "deepthroat",
        "tears",
        "drooling",
        "saliva",
        "closed_eyes",
        "blush",
    ),
    # ── Manual ────────────────────────────────────────────────────────────
    "handjob_dominant": (
        "handjob",
        "smirk",
        "looking_at_viewer",
        "looking_down",
        "smug",
    ),
    "footjob_dominant": (
        "footjob",
        "barefoot",
        "soles",
        "smug",
        "looking_down",
        "sitting",
    ),
    "playful_handjob": (
        "handjob",
        "smirk",
        "one_eye_closed",
        "tongue_out",
        "looking_at_viewer",
    ),
    "paizuri_scene": (
        "paizuri",
        "huge_breasts",
        "cum_on_breasts",
        "smirk",
        "looking_at_viewer",
        "topless",
    ),
    "thigh_sex_smug": (
        "thigh_sex",
        "thighhighs",
        "looking_at_viewer",
        "smug",
        "smirk",
        "looking_down",
    ),
    # ── Aftermath ─────────────────────────────────────────────────────────
    "after_sex_aftermath": (
        "after_sex",
        "cum_on_face",
        "cum_on_body",
        "ahegao",
        "drooling",
        "half-closed_eyes",
        "lying",
        "on_back",
        "sweat",
    ),
    "creampie_aftermath": (
        "after_vaginal",
        "cum_in_pussy",
        "blush",
        "lying",
        "on_back",
        "closed_eyes",
        "nude",
        "ahegao",
    ),
    "afterglow_tender": (
        "after_sex",
        "lying",
        "closed_eyes",
        "smile",
        "blush",
    ),
    "bukkake": (
        "bukkake",
        "cum_on_face",
        "cum_on_breasts",
        "cum_on_hair",
        "ahegao",
        "tongue_out",
        "open_mouth",
        "facial",
    ),
    # ── Solo ──────────────────────────────────────────────────────────────
    "masturbation_solo": (
        "masturbation",
        "female_masturbation",
        "spread_pussy",
        "fingering",
        "blush",
        "heart-shaped_pupils",
        "parted_lips",
        "nude",
    ),
    "squirting": (
        "squirting",
        "female_ejaculation",
        "spread_legs",
        "ahegao",
        "on_back",
        "convulsing",
        "nude",
    ),
    "vibrator_tease": (
        "vibrator_under_clothes",
        "blush",
        "embarrassed",
        "trembling",
        "parted_lips",
        "looking_at_viewer",
    ),
    # ── Exhibitionism ─────────────────────────────────────────────────────
    "public_exposure": (
        "bottomless",
        "no_panties",
        "embarrassed",
        "blush",
        "bare_legs",
        "park",
        "outdoors",
        "looking_away",
    ),
    "panty_shot_voyeur": (
        "skirt_lift",
        "wind_lift",
        "panties",
        "exposed_gusset",
        "pleated_skirt",
        "blush",
        "looking_back",
        "embarrassed",
    ),
    "lingerie_tease": (
        "lingerie",
        "bra",
        "panties",
        "garter_belt",
        "thighhighs",
        "smirk",
        "looking_at_viewer",
        "on_back",
    ),
    "shower_scene": (
        "bathroom",
        "shower",
        "steam",
        "wet_clothes",
        "blush",
        "embarrassed",
        "nude",
        "shiny_skin",
    ),
    # ── Breast play ───────────────────────────────────────────────────────
    "breast_play": (
        "nipple_sucking",
        "breast_sucking",
        "breast_grab",
        "areola_slip",
        "nipples",
        "blush",
        "topless",
    ),
    # ── Bondage / BDSM ────────────────────────────────────────────────────
    "femdom_dominant": (
        "smug",
        "looking_down",
        "bdsm",
        "leash",
        "thigh_boots",
        "corset",
        "spanking",
        "holding_whip",
    ),
    "bound_submissive": (
        "restrained",
        "tied_up",
        "ball_gag",
        "handcuffs",
        "blush",
        "embarrassed",
        "tearful",
        "nude",
    ),
    "shibari_suspension": (
        "shibari",
        "rope",
        "suspension_bondage",
        "bdsm",
        "ahegao",
        "nude",
        "blush",
    ),
    "captive_bound": (
        "tied_up",
        "restrained",
        "vaginal",
        "on_back",
        "tearful",
        "blush",
        "nude",
        "looking_away",
    ),
    # ── Group ─────────────────────────────────────────────────────────────
    "threesome_ffm": (
        "threesome",
        "ffm_threesome",
        "multiple_girls",
        "sweat",
        "blush",
    ),
    "tribadism_yuri": (
        "tribadism",
        "multiple_girls",
        "nude",
        "blush",
        "moaning",
        "looking_at_another",
    ),
    # ── Sleeping / Passive ────────────────────────────────────────────────
    "sleeping_grope": (
        "sleeping",
        "groping",
        "breast_grab",
        "blush",
        "closed_eyes",
    ),
    # ── Mood-driven ───────────────────────────────────────────────────────
    "yandere_possession": (
        "yandere",
        "looking_at_viewer",
        "vaginal",
        "restrained",
        "smirk",
        "heart-shaped_pupils",
        "nude",
        "blush",
    ),
    "cunnilingus_dominant": (
        "cunnilingus",
        "smug",
        "looking_down",
        "hand_on_another's_head",
        "thighhighs",
        "blush",
    ),
}


class NsfwActPreset(PresetNodeBase):
    PRESETS = NSFW_ACT_PRESETS
    PARAM = "act"
    LAYER = "nsfw_preset"


NODE_CLASS_MAPPINGS: dict[str, type] = {"UtilityNodesNsfwActPreset": NsfwActPreset}
NODE_DISPLAY_NAME_MAPPINGS: dict[str, str] = {"UtilityNodesNsfwActPreset": "NSFW Act"}
