from ._base import PresetNodeBase

# NSFW scene presets — bundle act/position/state/expression/setting tags
# that frequently appear together. Designed to layer on top of
# CharacterPreset (visuals) and PersonalityPreset (mood) via TagsBuild.
# Conflicts with non-NSFW clothing presets are resolved automatically
# (e.g. `nude`-containing presets drop competing outfit tags).
NSFW_SCENE_PRESETS: dict[str, tuple[str, ...]] = {
    # ── Existing presets ──────────────────────────────────────────────────
    "vanilla_missionary": (
        "missionary",
        "vaginal",
        "kissing",
        "french_kiss",
        "nude",
        "blush",
        "parted_lips",
        "closed_eyes",
        "on_back",
    ),
    "doggystyle": (
        "doggystyle",
        "sex_from_behind",
        "arched_back",
        "all_fours",
        "ahegao",
        "heart-shaped_pupils",
        "tongue_out",
        "nude",
    ),
    "mating_press": (
        "mating_press",
        "ahegao",
        "heart-shaped_pupils",
        "on_back",
        "sweat",
        "blush",
        "nude",
        "tongue_out",
    ),
    "cowgirl_riding": (
        "cowgirl_position",
        "vaginal",
        "moaning",
        "blush",
        "looking_at_viewer",
        "open_mouth",
        "smirk",
        "nude",
    ),
    "anal_focus": (
        "anal",
        "anal_doggystyle",
        "cum_in_ass",
        "spread_ass",
        "presenting",
        "ahegao",
        "on_stomach",
    ),
    "fellatio_pov": (
        "fellatio",
        "cum_in_mouth",
        "saliva",
        "saliva_trail",
        "closed_eyes",
        "blush",
        "kneeling",
    ),
    "paizuri_scene": (
        "paizuri",
        "huge_breasts",
        "cum_on_breasts",
        "smirk",
        "looking_at_viewer",
        "topless",
    ),
    "handjob_dominant": (
        "handjob",
        "smirk",
        "looking_at_viewer",
        "looking_down",
        "smug",
    ),
    "footjob_dominant": (
        "footjob",
        "barefoot",
        "soles",
        "smug",
        "looking_down",
        "sitting",
    ),
    "after_sex_aftermath": (
        "after_sex",
        "cum_on_face",
        "cum_on_body",
        "ahegao",
        "drooling",
        "half-closed_eyes",
        "lying",
        "on_back",
        "sweat",
    ),
    "bukkake": (
        "bukkake",
        "cum_on_face",
        "cum_on_breasts",
        "cum_on_hair",
        "ahegao",
        "tongue_out",
        "open_mouth",
        "facial",
    ),
    "squirting": (
        "squirting",
        "female_ejaculation",
        "spread_legs",
        "ahegao",
        "on_back",
        "convulsing",
        "nude",
    ),
    "masturbation_solo": (
        "masturbation",
        "female_masturbation",
        "spread_pussy",
        "fingering",
        "blush",
        "heart-shaped_pupils",
        "parted_lips",
        "bedroom",
        "nude",
    ),
    "lingerie_tease": (
        "lingerie",
        "bra",
        "panties",
        "garter_belt",
        "thighhighs",
        "smirk",
        "looking_at_viewer",
        "bedroom",
        "on_back",
    ),
    "first_time_shy": (
        "vaginal",
        "missionary",
        "embarrassed",
        "blush",
        "tearful",
        "parted_lips",
        "nude",
        "closed_eyes",
    ),
    "femdom_dominant": (
        "smug",
        "looking_down",
        "bdsm",
        "leash",
        "thigh_boots",
        "corset",
        "spanking",
        "holding_whip",
    ),
    "bound_submissive": (
        "restrained",
        "tied_up",
        "ball_gag",
        "handcuffs",
        "blush",
        "embarrassed",
        "tearful",
        "nude",
    ),
    "shibari_suspension": (
        "shibari",
        "rope",
        "suspension_bondage",
        "bdsm",
        "ahegao",
        "nude",
        "blush",
    ),
    "breast_play": (
        "nipple_sucking",
        "breast_sucking",
        "breast_grab",
        "areola_slip",
        "nipples",
        "blush",
        "topless",
    ),
    "public_exposure": (
        "bottomless",
        "no_panties",
        "embarrassed",
        "blush",
        "bare_legs",
        "park",
        "outdoors",
        "looking_away",
    ),
    "shower_scene": (
        "bathroom",
        "shower",
        "steam",
        "wet_clothes",
        "blush",
        "embarrassed",
        "nude",
        "shiny_skin",
    ),
    "threesome_ffm": (
        "threesome",
        "ffm_threesome",
        "multiple_girls",
        "sweat",
        "blush",
    ),
    "panty_shot_voyeur": (
        "skirt_lift",
        "wind_lift",
        "panties",
        "exposed_gusset",
        "pleated_skirt",
        "blush",
        "looking_back",
        "embarrassed",
    ),
    # ── New presets ───────────────────────────────────────────────────────
    "reverse_cowgirl": (
        "reverse_cowgirl_position",
        "vaginal",
        "moaning",
        "blush",
        "looking_back",
        "nude",
        "sweat",
    ),
    "prone_bone": (
        "prone_bone",
        "sex_from_behind",
        "ahegao",
        "nude",
        "on_stomach",
        "sweat",
        "heart-shaped_pupils",
    ),
    "cunnilingus_receive": (
        "cunnilingus",
        "spread_legs",
        "blush",
        "moaning",
        "closed_eyes",
        "nude",
        "on_back",
        "sweat",
    ),
    "vibrator_tease": (
        "vibrator_under_clothes",
        "blush",
        "embarrassed",
        "trembling",
        "parted_lips",
        "looking_at_viewer",
    ),
    "creampie_aftermath": (
        "after_vaginal",
        "cum_in_pussy",
        "blush",
        "lying",
        "on_back",
        "closed_eyes",
        "nude",
        "ahegao",
    ),
    "wall_slam": (
        "wall_slam",
        "standing_sex",
        "vaginal",
        "blush",
        "nude",
        "looking_at_viewer",
        "open_mouth",
    ),
    # ── Location-based (location sets context; layer with character preset) ─
    "examination_room": (
        "hospital",
        "indoors",
        "groping",
        "breast_grab",
        "blush",
        "embarrassed",
        "looking_at_viewer",
        "topless",
    ),
    "bedroom_grope": (
        "bedroom",
        "indoors",
        "groping",
        "breast_grab",
        "blush",
        "embarrassed",
        "looking_at_viewer",
    ),
    "outdoor_skirt_tease": (
        "shrine_outdoors",
        "outdoors",
        "skirt_lift",
        "no_panties",
        "blush",
        "looking_away",
        "embarrassed",
    ),
    "office_night": (
        "office",
        "indoors",
        "night",
        "vaginal",
        "on_back",
        "blush",
        "nude",
        "looking_at_viewer",
    ),
    "candlelit_ritual": (
        "candlelight",
        "indoors",
        "nude",
        "vaginal",
        "missionary",
        "blush",
        "looking_at_viewer",
    ),
    "locker_room_sex": (
        "locker_room",
        "indoors",
        "nude",
        "standing_sex",
        "vaginal",
        "blush",
        "embarrassed",
    ),
    # ── Act (clothed / restrained; layer with any character preset) ───────
    "clothed_sex": (
        "clothes_lift",
        "vaginal",
        "on_back",
        "blush",
        "embarrassed",
        "tearful",
    ),
    "captive_bound": (
        "tied_up",
        "restrained",
        "vaginal",
        "on_back",
        "tearful",
        "blush",
        "nude",
        "looking_away",
    ),
    "sleeping_grope": (
        "sleeping",
        "bedroom",
        "indoors",
        "groping",
        "breast_grab",
        "blush",
        "closed_eyes",
    ),
    # ── Mood-driven (layer with personality preset) ───────────────────────
    "yandere_possession": (
        "yandere",
        "looking_at_viewer",
        "vaginal",
        "restrained",
        "smirk",
        "heart-shaped_pupils",
        "nude",
        "blush",
    ),
    "cunnilingus_dominant": (
        "cunnilingus",
        "smug",
        "looking_down",
        "hand_on_another's_head",
        "thighhighs",
        "blush",
    ),
    "thigh_sex_smug": (
        "thigh_sex",
        "thighhighs",
        "looking_at_viewer",
        "smug",
        "smirk",
        "looking_down",
    ),
    "lotus_embrace": (
        "lotus_position",
        "vaginal",
        "kissing",
        "nude",
        "blush",
        "closed_eyes",
        "smile",
    ),
    # ── Position-focused ──────────────────────────────────────────────────
    "irrumatio_rough": (
        "irrumatio",
        "deepthroat",
        "tears",
        "drooling",
        "saliva",
        "closed_eyes",
        "blush",
    ),
    "full_nelson_ahegao": (
        "full_nelson",
        "vaginal",
        "ahegao",
        "heart-shaped_pupils",
        "nude",
        "sweat",
    ),
    "leg_lock_deep": (
        "leg_lock",
        "vaginal",
        "cum_in_pussy",
        "blush",
        "looking_at_viewer",
        "nude",
        "ahegao",
    ),
    "spitroast": (
        "spitroast",
        "fellatio",
        "vaginal",
        "ahegao",
        "nude",
        "sweat",
    ),
    "tribadism_yuri": (
        "tribadism",
        "multiple_girls",
        "nude",
        "blush",
        "moaning",
        "looking_at_another",
    ),
}


class NsfwScenePreset(PresetNodeBase):
    PRESETS = NSFW_SCENE_PRESETS
    PARAM = "scene"
    LAYER = "nsfw_preset"


NODE_CLASS_MAPPINGS: dict[str, type] = {"UtilityNodesNsfwScenePreset": NsfwScenePreset}
NODE_DISPLAY_NAME_MAPPINGS: dict[str, str] = {"UtilityNodesNsfwScenePreset": "NSFW Scene"}
