from ._base import PresetNodeBase

# SFW situation/scene presets. Each bundle combines location + time-of-day +
# atmosphere + composition + action cues for a coherent scene. Designed to
# layer on top of CharacterPreset / PersonalityPreset via TagsBuild — the
# scene tags rarely conflict with character tags, so layering is usually
# clean. NSFW counterparts live in nsfw_preset.py.
#
# All tags here are constrained to be registered in some tag node (enforced
# by test_situation_preset.py) so that the prompt stays inside the index
# we already trust.
SITUATION_PRESETS: dict[str, tuple[str, ...]] = {
    # ── Existing presets ──────────────────────────────────────────────────
    "after_school_classroom": (
        "classroom",
        "indoors",
        "afternoon",
        "sunset",
        "backlighting",
        "school_uniform",
        "looking_at_viewer",
    ),
    "school_commute_morning": (
        "outdoors",
        "morning",
        "sunlight",
        "city",
        "cherry_blossoms",
        "school_uniform",
        "school_bag",
        "walking",
        "looking_at_viewer",
    ),
    "summer_beach": (
        "beach",
        "ocean",
        "outdoors",
        "noon",
        "sunny",
        "swimsuit",
        "wind_lift",
        "looking_at_viewer",
    ),
    "summer_festival": (
        "outdoors",
        "night",
        "festival",
        "yukata",
        "geta",
        "holding_hands",
        "looking_at_viewer",
        "happy",
        "smile",
    ),
    "winter_cafe": (
        "indoors",
        "cafe",
        "afternoon",
        "holding_cup",
        "sweater",
        "scarf",
        "smile",
        "looking_at_viewer",
    ),
    "hot_spring": (
        "steam",
        "night",
        "moonlight",
        "naked_towel",
        "blush",
        "looking_at_viewer",
    ),
    "shrine_visit": (
        "shrine",
        "outdoors",
        "afternoon",
        "miko",
        "hakama",
        "looking_at_viewer",
        "smile",
    ),
    "park_picnic": (
        "park",
        "outdoors",
        "noon",
        "sunny",
        "sitting",
        "smile",
        "looking_at_viewer",
    ),
    "library_study": (
        "library",
        "indoors",
        "afternoon",
        "holding_book",
        "school_uniform",
        "glasses",
        "from_side",
    ),
    "gym_workout": (
        "gym",
        "indoors",
        "gym_uniform",
        "sports_bra",
        "sweat",
        "panting",
        "looking_at_viewer",
        "dynamic_pose",
    ),
    "karaoke_room": (
        "indoors",
        "night",
        "neon_lights",
        "holding_microphone",
        "singing",
        "smile",
        "open_mouth",
    ),
    "shopping_date": (
        "outdoors",
        "city",
        "afternoon",
        "holding_hands",
        "happy",
        "smile",
        "looking_at_viewer",
    ),
    "morning_routine": (
        "bedroom",
        "indoors",
        "morning",
        "sunlight",
        "stretching",
        "messy_hair",
        "sleepy",
    ),
    "cherry_blossom_park": (
        "park",
        "outdoors",
        "cherry_blossoms",
        "petals",
        "noon",
        "sunlight",
        "school_uniform",
        "smile",
        "looking_at_viewer",
    ),
    "rooftop_sunset": (
        "rooftop",
        "outdoors",
        "evening",
        "sunset",
        "backlighting",
        "wind_lift",
        "school_uniform",
        "looking_at_viewer",
    ),
    "street_snap_city": (
        "outdoors",
        "city",
        "street",
        "afternoon",
        "walking",
        "from_below",
        "looking_at_viewer",
    ),
    "kitchen_cooking": (
        "kitchen",
        "indoors",
        "morning",
        "apron",
        "cooking",
        "smile",
        "looking_at_viewer",
    ),
    "snowy_streetscape": (
        "outdoors",
        "city",
        "snow",
        "evening",
        "scarf",
        "coat",
        "mittens",
        "smile",
        "looking_at_viewer",
    ),
    # ── New presets ───────────────────────────────────────────────────────
    "gaming_night": (
        "bedroom",
        "indoors",
        "night",
        "gaming",
        "sitting",
        "looking_at_viewer",
        "smile",
    ),
    "aquarium_date": (
        "indoors",
        "afternoon",
        "sundress",
        "smile",
        "looking_at_viewer",
        "soft_lighting",
    ),
    "amusement_park": (
        "outdoors",
        "city",
        "noon",
        "sunny",
        "happy",
        "smile",
        "looking_at_viewer",
    ),
    "rainy_train_window": (
        "train_interior",
        "indoors",
        "raining",
        "evening",
        "looking_away",
        "coat",
        "scarf",
    ),
    "stargazing_rooftop": (
        "rooftop",
        "outdoors",
        "night",
        "moonlight",
        "clear_sky",
        "sitting",
        "smile",
    ),
    "music_room_practice": (
        "school",
        "indoors",
        "afternoon",
        "singing",
        "school_uniform",
        "holding_microphone",
        "smile",
    ),
    "autumn_stroll": (
        "park",
        "outdoors",
        "autumn_leaves",
        "falling_leaves",
        "afternoon",
        "smile",
        "coat",
        "looking_at_viewer",
    ),
    "late_night_diner": (
        "restaurant",
        "indoors",
        "night",
        "neon_lights",
        "eating",
        "holding_chopsticks",
        "smile",
    ),
    "dance_studio": (
        "indoors",
        "afternoon",
        "dancing",
        "leotard",
        "dynamic_pose",
        "looking_at_viewer",
    ),
    "concert_stage": (
        "stage",
        "indoors",
        "night",
        "spotlight",
        "singing",
        "holding_microphone",
        "smile",
        "sparkling_eyes",
    ),
    "spring_rain_street": (
        "outdoors",
        "city",
        "raining",
        "afternoon",
        "holding_umbrella",
        "looking_at_viewer",
        "smile",
    ),
    "cultural_festival": (
        "schoolyard",
        "outdoors",
        "afternoon",
        "school_uniform",
        "happy",
        "smile",
        "looking_at_viewer",
    ),
    # ── Character-context situations (location sets pairing; no costume tags)
    "hospital_ward": (
        # pairs naturally with nurse / healer chars
        "hospital",
        "indoors",
        "afternoon",
        "soft_lighting",
        "sitting",
        "smile",
        "looking_at_viewer",
    ),
    "dojo_practice": (
        # pairs naturally with fighter / samurai / kunoichi chars
        "indoors",
        "morning",
        "sunlight",
        "dynamic_pose",
        "determined",
        "serious",
    ),
    "ancient_ruins": (
        # pairs naturally with knight / samurai / warrior chars
        "ruins",
        "outdoors",
        "evening",
        "dramatic_lighting",
        "dynamic_pose",
        "serious",
    ),
    "enchanted_forest": (
        # pairs naturally with elf / witch / ranger chars
        "forest",
        "outdoors",
        "afternoon",
        "natural_lighting",
        "mist",
        "standing",
        "looking_ahead",
    ),
    "magic_workshop": (
        # pairs naturally with witch / mage chars
        "indoors",
        "night",
        "candlelight",
        "sparkles",
        "serious",
        "holding_wand",
    ),
    "idol_backstage": (
        # pairs naturally with idol chars
        "stage",
        "indoors",
        "night",
        "spotlight",
        "holding_microphone",
        "smile",
        "looking_at_viewer",
    ),
    "beach_sports": (
        # pairs naturally with cheerleader / athletic chars
        "beach",
        "outdoors",
        "noon",
        "sunny",
        "dynamic_pose",
        "smile",
        "happy",
    ),
    "detective_office": (
        # pairs naturally with detective char
        "office",
        "indoors",
        "afternoon",
        "serious",
        "looking_to_the_side",
    ),
    "harbor_morning": (
        # pairs naturally with pirate / navigator chars
        "outdoors",
        "ocean",
        "morning",
        "windy",
        "sunlight",
        "smile",
        "looking_at_viewer",
    ),
    "church_interior": (
        # pairs naturally with nun / fantasy_cleric chars
        "church",
        "indoors",
        "afternoon",
        "soft_lighting",
        "standing",
        "smile",
        "looking_at_viewer",
    ),
    "japanese_garden": (
        # pairs naturally with samurai / miko / shrine_dancer chars
        "garden",
        "outdoors",
        "afternoon",
        "sunlight",
        "petals",
        "standing",
        "smile",
    ),
    "race_grid": (
        # pairs naturally with race_queen char
        "outdoors",
        "noon",
        "sunny",
        "dynamic_pose",
        "smile",
        "looking_at_viewer",
    ),
    "neon_city_night": (
        # pairs naturally with android / futuristic_idol chars
        "outdoors",
        "city",
        "night",
        "neon_lights",
        "neon_trim",
        "walking",
        "looking_at_viewer",
    ),
    "gothic_cathedral": (
        # pairs naturally with vampire / gothic_lolita / nun chars
        "church",
        "indoors",
        "night",
        "candlelight",
        "dramatic_lighting",
        "standing",
        "serious",
    ),
    "outdoor_training": (
        # pairs naturally with military / knight / kunoichi chars
        "outdoors",
        "afternoon",
        "sunlight",
        "dynamic_pose",
        "determined",
        "serious",
    ),
    "cafe_morning_shift": (
        # pairs naturally with cafe_waitress char (worker POV)
        "cafe",
        "indoors",
        "morning",
        "sunlight",
        "smile",
        "looking_at_viewer",
    ),
    "locker_room": (
        # pairs naturally with athletic / sports chars
        "locker_room",
        "indoors",
        "afternoon",
        "looking_at_viewer",
    ),
}


class SituationPreset(PresetNodeBase):
    PRESETS = SITUATION_PRESETS
    PARAM = "situation"
    LAYER = "situation"


NODE_CLASS_MAPPINGS: dict[str, type] = {"UtilityNodesSituationPreset": SituationPreset}
NODE_DISPLAY_NAME_MAPPINGS: dict[str, str] = {"UtilityNodesSituationPreset": "Situation"}
